# Box domain dimensions.
[domain]
xmin = -500.0
ymin = -500.0
zmin = -3000.0
xmax = 500.0
ymax = 500.0
zmax = -2000.0

# Box subdomain dimensions (for fractures)
[subdomain]
xmin = -50.0
ymin = -50.0
zmin = -2550.0
xmax = 50.0
ymax = 50.0
zmax = -2450.0

# Main constraints supported by Frackit.
[constraints]
min_distance = 5 # Minimum distance between fractures.
min_intersecting_angle_deg_self = 30.0 # Minimum angle between intersecting fractures of the same family.
min_intersecting_angle_deg_other = 40.0 # Minimum angle between intersecting fractures of different families.
min_intersection_magnitude = 5 # Minimum magnitude of intersection between fractures.
min_intersection_distance = 5 # Minimum distance between non-intersecting fractures.

# Fracture properties.
[sampler]
num = 3 # number of fracture families to sample. Each family is defined in a section [sampler.i], where i is the family index starting from 1.

# Family #1.
# Target 5 disks, with major axis length mean 50 and stddev 10,
# minor axis length mean 50 and stddev 5, and rotation angles
# with mean 0 and stddev 7.5 degrees.
[sampler.1]
target_num = 5 # number of fractures to sample for this family
type = "disks" # "disks" or "quads"

# All distributions here are normal distributions, defined by a mean and a standard deviation.
[sampler.1.major_axis_length]
mean = 50.0 # mean of the major axis length distribution
stddev = 10.0 # standard deviation of the major axis length distribution

[sampler.1.minor_axis_length]
mean = 50.0 # mean of the minor axis length distribution
stddev = 5.0 # standard deviation of the minor axis length distribution

[sampler.1.rotation_deg.x]
mean = 0.0 # mean of the rotation angle distribution around x-axis (in degrees)
stddev = 7.5 # standard deviation of the rotation angle distribution around x-axis (in degrees)

[sampler.1.rotation_deg.y]
mean = 0.0 # mean of the rotation angle distribution around y-axis (in degrees)
stddev = 7.5 # standard deviation of the rotation angle distribution around y-axis (in degrees)

[sampler.1.rotation_deg.z]
mean = 0.0 # mean of the rotation angle distribution around z-axis (in degrees)
stddev = 7.5 # standard deviation of the rotation angle distribution around z-axis (in degrees)

# Fracture family 2. Similar to family 1, but with different parameters.
[sampler.2]
target_num = 7
type = "disks"

[sampler.2.major_axis_length]
mean = 50.0
stddev = 10.0

[sampler.2.minor_axis_length]
mean = 50.0
stddev = 5.0

[sampler.2.rotation_deg.x]
mean = 90.0
stddev = 7.5

[sampler.2.rotation_deg.y]
mean = 45.0
stddev = 7.5

[sampler.2.rotation_deg.z]
mean = 20.0
stddev = 7.5

# Fracture family 2. Similar to family 1, but with different parameters.
[sampler.3]
target_num = 10
type = "quads"

[sampler.3.strike_deg]
mean = 50.0
stddev = 10.0

[sampler.3.dip_deg]
mean = 30.0
stddev = 5.0

[sampler.3.strike_length]
min = 40.0
max = 60.0

[sampler.3.dip_length]
min = 25.0
max = 35.0